[2025-04-05 16:23:24,630] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:23:24,634] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:23:28,376] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:23:28] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:23:28,594] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:23:28] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:23:28,596] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:23:28] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:23:28,600] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:23:28] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:23:28,808] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:23:28] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:23:28,815] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:23:28] "[36mGET /openapi/swagger/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:23:32,663] ERROR log_exception() L875  Exception on /perform-rescue [GET] - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "D:\Desenvolvimento\PUC\rescue-api\app.py", line 245, in perform_recue_point
    closest_rescue_point = closest_point(vehicule, rescue_points)
  File "D:\Desenvolvimento\PUC\rescue-api\model\rescue_point.py", line 69, in closest_point
    shortest_distance = calculate_distance(reference_point, next_point)
  File "D:\Desenvolvimento\PUC\rescue-api\model\rescue_point.py", line 64, in calculate_distance
    return ((point1.latitude - point2.latitude)**2 + (point1.longitude - point2.longitude)**2)**0.5
                                                      ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'str'
[2025-04-05 16:23:32,671] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:23:32] "[35m[1mGET /perform-rescue?id=1 HTTP/1.1[0m" 500 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:24:45,015] ERROR log_exception() L875  Exception on /perform-rescue [GET] - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "D:\Desenvolvimento\PUC\rescue-api\app.py", line 245, in perform_recue_point
    closest_rescue_point = closest_point(vehicule, rescue_points)
  File "D:\Desenvolvimento\PUC\rescue-api\model\rescue_point.py", line 69, in closest_point
    shortest_distance = calculate_distance(reference_point, next_point)
  File "D:\Desenvolvimento\PUC\rescue-api\model\rescue_point.py", line 64, in calculate_distance
    return ((point1.latitude - point2.latitude)**2 + (point1.longitude - point2.longitude)**2)**0.5
                                                      ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'str'
[2025-04-05 16:24:45,021] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:24:45] "[35m[1mGET /perform-rescue?id=1 HTTP/1.1[0m" 500 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:25:22,052] ERROR log_exception() L875  Exception on /perform-rescue [GET] - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "D:\Desenvolvimento\PUC\rescue-api\app.py", line 245, in perform_recue_point
    closest_rescue_point = closest_point(vehicule, rescue_points)
  File "D:\Desenvolvimento\PUC\rescue-api\model\rescue_point.py", line 69, in closest_point
    shortest_distance = calculate_distance(reference_point, next_point)
  File "D:\Desenvolvimento\PUC\rescue-api\model\rescue_point.py", line 64, in calculate_distance
    return ((point1.latitude - point2.latitude)**2 + (point1.longitude - point2.longitude)**2)**0.5
                                                      ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'str'
[2025-04-05 16:25:22,088] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:25:22] "[35m[1mGET /perform-rescue?id=1 HTTP/1.1[0m" 500 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:25:42,665] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:25:42,666] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:25:58,483] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:25:58] "POST /generate-rescue-point HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:26:45,191] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:26:45] "POST /vehicule HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:27:14,040] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:27:14] "GET /rescue-point HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
